# This is a workflow that echo's committer's name & email-id & is triggered on push

name: Committer workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2

#    - name: Commit Hash info 3
#      run: git log -1 --format="%an %ae" d244784

#    - name: get sha value
#      run: |
#        GIT_SHA=${{ github.sha }}
#        echo "sha value is: $GIT_SHA"

#    - name: get hash value
#      run: |
#        GIT_HASH=$( git rev-parse --short "$GITHUB_SHA" )
#        echo "hash value is: $GIT_HASH"
    
    - name: consolidated
      run: |
        GIT_HASH=$( git rev-parse --short "$GITHUB_SHA" )
        echo "hash value is: $GIT_HASH"
        git log -1 --format="%an %ae" "$GIT_HASH"

        COMMITTER_ID=$( git log -1 --format="%an" "$GIT_HASH" )
        COMMITTER_EMAIL=$( git log -1 --format="%ae" "$GIT_HASH" )
        
        echo "Committer's id is: $COMMITTER_ID"
        echo "Committer's email is: $COMMITTER_EMAIL"
    
